SquareSolver: inout.cpp File Reference
inout.cpp File Reference
#include <stdio.h>
#include <cassert>
#include "solver.h"
Functions
void input_coeffs (Polynome *eq)
void print_roots (Polynome *eq)
Function Documentation
input_coeffs()
void input_coeffs (Polynome * eq)
Tests solve_square until the end of test file
Parameters
test_file pointer to the file with reference values
Returns
-1 in case of error, otherwise 0
Parameters
eq pointer to a Polynome structure Inputs coeffs of the given polynome
Definition at line 7 of file inout.cpp.
{
    assert(eq != NULL);
    printf("Enter a, b, c: ");
    while (scanf("%lf %lf %lf", &eq->a, &eq->b, &eq->c) != 3) { // EOF?
        clear_buf();
        printf("Wrong input, try again\n"); // retry
    }
}
References Polynome::a, Polynome::b, and Polynome::c.
Referenced by main().
print_roots()
void print_roots (Polynome * eq)
Parameters
eq pointer to a Polynome structure
Definition at line 18 of file inout.cpp.
{
    assert(eq != NULL);
    switch (solve_square(eq)) {
        case 0:
            printf("No roots\n");
            break;
        case 1:
            printf("Root: %g\n", eq->x1);
            break;
        case 2:
            printf("Roots: %g %g\n", eq->x1, eq->x2);
            break;
        case SS_INF_ROOTS:
            printf("Infinte number of roots\n");
            break;
        default:
            printf("Error: unknown case\n");
    }
}
References solve_square(), SS_INF_ROOTS, Polynome::x1, and Polynome::x2.
Referenced by main().