SquareSolver: main.cpp File Reference
main.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <cassert>
#include "solver.h"
Functions
int main (int argc, char *argv[])
Variables
const int MAXLEN = 1000
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 9 of file main.cpp.
{
    printf("# Square equation solver\n"
           "# (c) Victor Baldin, 2023\n");
    if (argc == 3 && !strncmp("--test", argv[1], MAXLEN)) { // key --help , --test filename
        // run tests
        printf("# Running test\n");
        FILE *test_file = fopen(argv[2], "r");
        assert(test_file != NULL);
        return ss_test(test_file);
    }
    if (argc == 2 && !strncmp("--help", argv[1], MAXLEN)) { //moar help
        printf("square_solver solves the quadratic equation ax^2 + bx + c, "
               "where a, b, c is real numbers\n"
               "Run ./square_solver and enter coeffitients a, b, c in format \"a b c\"\n");
        return 0;
    }
    Polynome equation = {};
    Polynome *eq = &equation;
    input_coeffs(eq);
    print_roots(eq);
    return 0;
}
References input_coeffs(), MAXLEN, print_roots(), and ss_test().
Variable Documentation
MAXLEN
const int MAXLEN = 1000
Definition at line 7 of file main.cpp.
Referenced by main().