SquareSolver: solver.h File Reference
solver.h File Reference
#include <stdio.h>
Classes
struct Polynome
struct TestData
Macros
#define NDEBUG
Functions
int solve_square (Polynome *eq)
bool isequal (double a, double b)
void input_coeffs (Polynome *eq)
void print_roots (Polynome *eq)
int ss_test (FILE *test_file)
Variables
const int SS_INF_ROOTS = 3
const int ERROR = -1
Macro Definition Documentation
NDEBUG
#define NDEBUG
Definition at line 6 of file solver.h.
Function Documentation
input_coeffs()
void input_coeffs (Polynome * eq)
Tests solve_square until the end of test file
Parameters
test_file pointer to the file with reference values
Returns
-1 in case of error, otherwise 0
Parameters
eq pointer to a Polynome structure Inputs coeffs of the given polynome
Definition at line 7 of file inout.cpp.
{
    assert(eq != NULL);
    printf("Enter a, b, c: ");
    while (scanf("%lf %lf %lf", &eq->a, &eq->b, &eq->c) != 3) { // EOF?
        clear_buf();
        printf("Wrong input, try again\n"); // retry
    }
}
References Polynome::a, Polynome::b, and Polynome::c.
Referenced by main().
isequal()
bool isequal (double a, double b)
Two doubles comparison
Parameters
a
b
Returns
1 if close enough, 0 if not
Definition at line 12 of file solve.cpp.
{
    const double prec = 1.0e-7; // точность сравнения
    return (fabs(a - b) <= prec) || (isnan(a) && isnan(b));
}
Referenced by solve_square().
print_roots()
void print_roots (Polynome * eq)
Parameters
eq pointer to a Polynome structure
Definition at line 18 of file inout.cpp.
{
    assert(eq != NULL);
    switch (solve_square(eq)) {
        case 0:
            printf("No roots\n");
            break;
        case 1:
            printf("Root: %g\n", eq->x1);
            break;
        case 2:
            printf("Roots: %g %g\n", eq->x1, eq->x2);
            break;
        case SS_INF_ROOTS:
            printf("Infinte number of roots\n");
            break;
        default:
            printf("Error: unknown case\n");
    }
}
References solve_square(), SS_INF_ROOTS, Polynome::x1, and Polynome::x2.
Referenced by main().
solve_square()
int solve_square (Polynome * eq)
Solves the quadratic equation a*x^2+b*x+c=0
Parameters
eq pointer to a Polynome structure
Returns
number of roots of the polynome
Definition at line 18 of file solve.cpp.
{
    assert(isfinite(eq->a));
    assert(isfinite(eq->b));
    assert(isfinite(eq->c));
    if (isequal(eq->a, 0)) {
        assert(eq != NULL);
        int nroots = do_solve_linear(eq);
        return nroots;
    }
    if (isequal(eq->c, 0)) {
        if (!isequal(eq->b, 0)) {
            eq->x2 = 0;
            eq->c = eq->b;
            eq->b = eq->a;
            eq->a = 0;
            do_solve_linear(eq);
            return 2;
        }
        else {
            eq->x1 = 0;
            return 1;
        }
    }
    else {
        double D = eq->b * eq->b - 4 * eq->a * eq->c;
        if (isequal(D, 0)) {
            eq->x1 = -eq->b / (2 * eq->a);
            return 1;
        }
        else {
            if (D > 0) {
                double sqrt_D = sqrt(D);
                eq->x1 = (-eq->b - sqrt_D) / (2 * eq->a);
                eq->x2 = (-eq->b + sqrt_D) / (2 * eq->a);
                return 2;
            }
            else {
                return 0;
            }
        }
    }
}
References Polynome::a, Polynome::b, Polynome::c, isequal(), Polynome::x1, and Polynome::x2.
Referenced by print_roots().
ss_test()
int ss_test (FILE * test_file)
Definition at line 14 of file solve_test.cpp.
{
    int test_res = 0;
    int num = 0; // test number
    int succeed = 0; // number of succeed tests
    TestData test_data = {};
    TestData *data = &test_data;
    fscanf(test_file, "a,b,c,root1,root2,ans");
    while (!feof(test_file)) {
        int n_arg = fscanf(test_file,
            "%lf, %lf, %lf, %lf, %lf, %d",
            &(data->a), &(data->b), &(data->c),
            &(data->x1_ref), &(data->x2_ref), &(data->nroots_ref)); //\n in end of file
        if (n_arg == EOF) {
            break;
        }
        if (n_arg != 6) {
            printf("wrong input in test file\n");
            return -1;
        };
        num++;
        assert(data != NULL);
        if (run_test(num, data) == -1) {
            test_res = -1;
        }
        else {
            succeed++;
        }
    }
    printf("%d/%d tests succeed\n", succeed, num);
    return test_res;
}
References TestData::a, TestData::b, TestData::c, TestData::nroots_ref, TestData::x1_ref, and TestData::x2_ref.
Referenced by main().
Variable Documentation
ERROR
const int ERROR = -1
Definition at line 9 of file solver.h.
SS_INF_ROOTS
const int SS_INF_ROOTS = 3
Definition at line 8 of file solver.h.
Referenced by print_roots().