SquareSolver: solve.cpp File Reference
solve.cpp File Reference
#include <math.h>
#include <assert.h>
#include "solver.h"
Functions
bool isequal (double a, double b)
int solve_square (Polynome *eq)
Function Documentation
isequal()
bool isequal (double a, double b)
Two doubles comparison
Parameters
a
b
Returns
1 if close enough, 0 if not
Definition at line 12 of file solve.cpp.
{
    const double prec = 1.0e-7; // точность сравнения
    return (fabs(a - b) <= prec) || (isnan(a) && isnan(b));
}
Referenced by solve_square().
solve_square()
int solve_square (Polynome * eq)
Solves the quadratic equation a*x^2+b*x+c=0
Parameters
eq pointer to a Polynome structure
Returns
number of roots of the polynome
Definition at line 18 of file solve.cpp.
{
    assert(isfinite(eq->a));
    assert(isfinite(eq->b));
    assert(isfinite(eq->c));
    if (isequal(eq->a, 0)) {
        assert(eq != NULL);
        int nroots = do_solve_linear(eq);
        return nroots;
    }
    if (isequal(eq->c, 0)) {
        if (!isequal(eq->b, 0)) {
            eq->x2 = 0;
            eq->c = eq->b;
            eq->b = eq->a;
            eq->a = 0;
            do_solve_linear(eq);
            return 2;
        }
        else {
            eq->x1 = 0;
            return 1;
        }
    }
    else {
        double D = eq->b * eq->b - 4 * eq->a * eq->c;
        if (isequal(D, 0)) {
            eq->x1 = -eq->b / (2 * eq->a);
            return 1;
        }
        else {
            if (D > 0) {
                double sqrt_D = sqrt(D);
                eq->x1 = (-eq->b - sqrt_D) / (2 * eq->a);
                eq->x2 = (-eq->b + sqrt_D) / (2 * eq->a);
                return 2;
            }
            else {
                return 0;
            }
        }
    }
}
References Polynome::a, Polynome::b, Polynome::c, isequal(), Polynome::x1, and Polynome::x2.
Referenced by print_roots().