SquareSolver: solve_test.cpp File Reference
solve_test.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "solver.h"
Functions
int solve_test ()
Function Documentation
solve_test()
int solve_test ()
Unit test for solve_square(). Reads csv file with valid values. Test file must contain the first "a,b,c,root1,root2,ans" string as a header.
Returns
0 if success, -1 if test failed
Definition at line 6 of file solve_test.cpp.
                 {
    FILE *test_file = fopen("test_values.csv", "r");      // чтение файла с тестовыми значениями
    double a = NAN, b = NAN, c = NAN;
    double roots[2] = {NAN, NAN};                         // массив корней, который заполняется функцией solve
    double valid_roots[2] = {NAN, NAN};                   // конрольные значения корней, полученные из файла
    int ans = 0;                                          // возвращаемое значение функции solve
    int valid_ans = 0;                                    // контрольное значение функции solve
    int res = 0;                                          // результат тестирования
    fscanf(test_file, "a,b,c,root1,root2,ans");           // проверка на наличие пояснений в test_file
    while (!feof(test_file)) {
        int n_arg = fscanf(test_file, "%lf, %lf, %lf, %lf, %lf, %d",
                &a, &b, &c, &valid_roots[0], &valid_roots[1], &valid_ans);
        if (n_arg != 6 && n_arg != EOF) {
            printf("Invalid test values\n");
            return -1;
        }
        else {
            ans = solve_square(roots, a, b, c);
            if (ans == valid_ans &&
                    is_equal(roots[0], valid_roots[0]) && is_equal(roots[1], valid_roots[1])) {
                printf("OK\n");
                continue;
            }
            else {
                printf("Test failed on values: a = %g, b = %g, c = %g\n",
                                               a, b, c);
                res = -1;
            }
        }
    }
    if (res == 0)
        printf("Tests OK\n");
    fclose(test_file);
    return res;
}
References is_equal(), and solve_square().
Referenced by main().